version: '3.7'

volumes:
  prometheus_data:
    external: true
  grafana_data:
    external: true

services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - /Users/jeonghyeonhong/Documents/github/v1-gateway/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    ports:
      - "9090:9090"
    restart: always

  grafana:
    image: grafana/grafana
    container_name: grafana
    depends_on:
      - prometheus
    user: "${GRAFANA_USER_ID}:${GRAFANA_PASSWORD}"
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    restart: always
